FROM node:14

# https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/opt/google/chrome-unstable/chrome

RUN mkdir /var/app
WORKDIR /var/app/


COPY ./package.json /var/app/
COPY ./Gruntfile.js /var/app/
COPY ./index.html /var/app/
COPY ./blog.html /var/app/

RUN npm -v
RUN  npm install -g grunt-cli
#RUN sudo npm install puppeteer --unsafe-perm=true --allow-root
RUN     npm install 
#RUN     bower install --allow-root
#RUN npm install util -g
RUN grunt -d

RUN cat generated_index.html

# #RUN yarn install
# COPY . /var/app/

#ENTRYPOINT ["/var/app/entrypoint.sh"]
#CMD ["run"]
EXPOSE  9000